services:
  #Encryption microservice
  build-production-encryption-service:
    image: ghcr.io/funixproductions/funixproductions-api-encryption:${IMAGE_TAG}
    build:
      context: .
      args:
        service_name: encryption
        service_base_dir: encryption
    platform: "linux/arm64"

  #User microservice
  build-production-user-service:
    image: ghcr.io/funixproductions/funixproductions-api-user:${IMAGE_TAG}
    build:
      context: .
      args:
        service_name: user
        service_base_dir: user
    platform: "linux/arm64"

  #Google microservices - Google Auth
  build-production-google-auth-service:
    image: ghcr.io/funixproductions/funixproductions-api-google-auth:${IMAGE_TAG}
    build:
      context: .
      args:
        service_name: google-auth
        service_base_dir: google/auth
    platform: "linux/arm64"


  #Google microservices - Google Gmail
  build-production-google-gmail-service:
    image: ghcr.io/funixproductions/funixproductions-api-google-gmail:${IMAGE_TAG}
    build:
      context: .
      args:
        service_name: google-gmail
        service_base_dir: google/gmail
    platform: "linux/arm64"

  #Google microservices - Google reCaptcha
  build-production-google-recaptcha-service:
    image: ghcr.io/funixproductions/funixproductions-api-google-recaptcha:${IMAGE_TAG}
    build:
      context: .
      args:
        service_name: google-recaptcha
        service_base_dir: google/reCaptcha
    platform: "linux/arm64"

  #Accounting - Calculator ursaff and impots.gouv service
  build-production-accounting-service:
    image: ghcr.io/funixproductions/funixproductions-api-accounting:${IMAGE_TAG}
    build:
      context: .
      args:
        service_name: accounting
        service_base_dir: accounting
    platform: "linux/arm64"

  #Payment - PayPal service
  build-production-payment-paypal-service:
    image: ghcr.io/funixproductions/funixproductions-api-payment-paypal:${IMAGE_TAG}
    build:
      context: .
      args:
        service_name: payment-paypal
        service_base_dir: payment/paypal
    platform: "linux/arm64"

  #Payment - Billing service
  build-production-payment-billing-service:
    image: ghcr.io/funixproductions/funixproductions-api-payment-billing:${IMAGE_TAG}
    build:
      context: .
      args:
        service_name: payment-billing
        service_base_dir: payment/billing
    platform: "linux/arm64"

  #Twitch - Auth service
  build-production-twitch-auth-service:
    image: ghcr.io/funixproductions/funixproductions-api-twitch-auth:${IMAGE_TAG}
    build:
      context: .
      args:
        service_name: twitch-auth
        service_base_dir: twitch/auth
    platform: "linux/arm64"

  #Twitch - EventSub service
  build-production-twitch-eventsub-service:
    image: ghcr.io/funixproductions/funixproductions-api-twitch-eventsub:${IMAGE_TAG}
    build:
      context: .
      args:
        service_name: twitch-eventsub
        service_base_dir: twitch/eventsub
    platform: "linux/arm64"

  #Twitch - Reference service
  build-production-twitch-reference-service:
    image: ghcr.io/funixproductions/funixproductions-api-twitch-reference:${IMAGE_TAG}
    build:
      context: .
      args:
        service_name: twitch-reference
        service_base_dir: twitch/reference
    platform: "linux/arm64"
