create table accounting_income
(
    id                          bigint generated by default as identity primary key,
    created_at                  timestamp not null,
    updated_at                  timestamp,
    uuid                        varchar(255)     not null constraint UK_accounting_income_public_id unique,
    income_name                 varchar(255)     not null,
    income_description          varchar(255)     not null,
    amount                      double precision not null
);

create table accounting_product
(
    id                          bigint generated by default as identity primary key,
    created_at                  timestamp        not null,
    updated_at                  timestamp,
    uuid                        varchar(255)     not null constraint UK_accounting_product_public_id unique,
    product_name                varchar(255)     not null,
    product_description         varchar(255)     not null,
    monthly                     boolean          not null,
    is_eu                       boolean          not null,
    is_physical                 boolean          not null,
    amount_ht                   double precision not null,
    amount_tax                  double precision not null
);
