create table paypal_plans
(
    id              bigint generated by default as identity primary key,
    created_at      timestamp     not null,
    updated_at      timestamp,
    uuid            varchar(255)  not null constraint UK_paypal_plan_public_id unique,
    plan_id         varchar(400),
    name            varchar(255)  not null,
    description     varchar(1000)  not null,
    image_url       varchar(500)  not null,
    home_url        varchar(500)  not null,
    price           double precision not null,
    project_name    varchar(255)  not null
);

create table paypal_subscriptions
(
    id                 bigint generated by default as identity primary key,
    created_at         timestamp     not null,
    updated_at         timestamp,
    uuid               varchar(255)  not null constraint UK_paypal_subscription_public_id unique,
    plan_id            bigint        not null constraint paypal_subscription_link_plan references paypal_plans,
    funix_prod_user_id varchar(300)  not null,
    subscription_id    varchar(400),
    active             boolean       not null,
    cycles_completed   int           not null,
    last_payment_date  timestamp,
    next_payment_date  timestamp
);
