create table api_users
(
    id         bigint generated by default as identity primary key,
    created_at timestamp     not null,
    updated_at timestamp,
    uuid       varchar(255)  not null constraint UK_user_public_id unique,
    banned     boolean       not null,
    email      varchar(255)  not null,
    password   varchar(2000) not null,
    role       varchar(255)  not null,
    username   varchar(255)  not null constraint UK_user_username unique
);

create table api_users_tokens
(
    id              bigint generated by default as identity primary key,
    created_at      timestamp     not null,
    updated_at      timestamp,
    uuid            varchar(255)  not null constraint UK_token_public_id unique,
    expiration_date timestamp,
    token           varchar(2000) not null constraint UK_api_token unique,
    user_id         bigint        not null constraint token_link_user references api_users
);
