create table user_password_reset
(
    id              bigint generated by default as identity primary key,
    created_at      timestamp     not null,
    updated_at      timestamp,
    uuid            varchar(255)  not null constraint UK_user_reset_token_public_id unique,
    origin          varchar(255)  not null,
    reset_token     varchar(2000) not null constraint UK_api_reset_token unique,
    user_id         bigint        not null constraint reset_token_link_user references api_users
);
