-- Create table for paypal_orders
CREATE TABLE paypal_orders (
                               id              bigint generated by default as identity primary key,
                               created_at      timestamp     not null,
                               updated_at      timestamp,
                               uuid            varchar(255)  not null constraint UK_paypal_order_public_id unique,
                               order_id VARCHAR(255) constraint UK_paypal_order_id unique,
                               user_id VARCHAR(255),
                               user_email VARCHAR(255) NOT NULL,
                               username VARCHAR(255) NOT NULL,
                               origin_request VARCHAR(255) NOT NULL,
                               card_payment BOOLEAN NOT NULL,
                               paid BOOLEAN NOT NULL,
                               vat_information VARCHAR(255)
);
