create table api_users
(
    id         bigint generated by default as identity primary key,
    created_at timestamp     not null,
    updated_at timestamp,
    uuid       varchar(255)  not null constraint UK_user_public_id unique,
    banned     boolean       not null,
    email      varchar(255)  not null,
    password   varchar(2000) not null,
    role       varchar(255)  not null,
    username   varchar(255)  not null constraint UK_user_username unique
);

create table api_users_tokens
(
    id              bigint generated by default as identity primary key,
    created_at      timestamp     not null,
    updated_at      timestamp,
    uuid            varchar(255)  not null constraint UK_token_public_id unique,
    expiration_date timestamp,
    token           varchar(2000) not null constraint UK_api_token unique,
    user_id         bigint        not null constraint token_link_user references api_users
);

create table twitch_client_tokens
(
    id                    bigint generated by default as identity primary key,
    created_at            timestamp(6) not null,
    updated_at            timestamp(6),
    uuid                  varchar(255) not null constraint twitch_client_tokens_public_id unique,
    access_token          varchar(255) not null constraint twitch_client_tokens_access_token unique,
    expiration_date_token timestamp(6) not null,
    o_auth_code           varchar(255) not null constraint twitch_client_tokens_oauth unique,
    refresh_token         varchar(255) not null constraint twitch_client_tokens_refresh unique,
    twitch_user_id        varchar(255) not null,
    twitch_username       varchar(255) not null,
    user_id               bigint       not null constraint twitch_client_tokens_link_user references api_users
);

create table twitch_event_sub_streamers
(
    id            bigint generated by default as identity primary key,
    created_at    timestamp        not null,
    updated_at    timestamp,
    uuid          varchar(255)     not null constraint UK_twitch_event_sub_streamers_public_id unique,
    streamer_id   varchar(255)     not null constraint UK_twitch_event_sub_streamers_st_id unique
);
