apiVersion: apps/v1
kind: Deployment

metadata:
  name: encryption-microservice-deployment
  namespace: 'funixproductions'
  labels:
    app: springboot
    service: encryption

spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
      service: encryption
  template:
    metadata:
      namespace: 'funixproductions'
      annotations:
        build-time: "TIME-UPDATE-BUILD-FNG"
      labels:
        app: springboot
        service: encryption
    spec:
      containers:
        - name: springboot-encryption
          image: ghcr.io/funixproductions/funixproductions-api-encryption:latest
          ports:
            - containerPort: 80
          resources:
            limits:
                memory: "750Mi"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: APP_PORT
              value: '80'
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: encryption-secret
                  key: encryption-key
            - name: ENCRYPTION_IV
              valueFrom:
                secretKeyRef:
                  name: encryption-secret
                  key: encryption-iv-key

---

apiVersion: v1
kind: Service

metadata:
  namespace: 'funixproductions'
  name: encryption

spec:
  type: ClusterIP
  selector:
    app: springboot
    service: encryption
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
