apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-paypal-microservice-deployment
  namespace: 'funixproductions'
  labels:
    app: springboot
    service: payment-paypal

spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
      service: payment-paypal
  template:
    metadata:
      namespace: 'funixproductions'
      annotations:
        build-time: "TIME-UPDATE-BUILD-FNG"
      labels:
        app: springboot
        service: payment-paypal
    spec:
      containers:
        - name: springboot-payment-paypal
          image: ghcr.io/funixproductions/funixproductions-api-payment-paypal:latest
          ports:
            - containerPort: 80
          resources:
            limits:
                memory: "1024Mi"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: APP_PORT
              value: '80'
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: postgres-url
                  name: postgres-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: paypal-secret
                  key: paypal-client-id
            - name: PAYPAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: paypal-secret
                  key: paypal-client-secret
            - name: PAYPAL_WEBHOOK_ID
              valueFrom:
                secretKeyRef:
                  name: paypal-secret
                  key: paypal-webhook-id
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: sentry-funixprod-api-key

---

apiVersion: v1
kind: Service

metadata:
  namespace: 'funixproductions'
  name: payment-paypal

spec:
  type: ClusterIP
  selector:
    app: springboot
    service: payment-paypal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
