create table twitch_client_tokens
(
    id                    bigint generated by default as identity primary key,
    created_at            timestamp(6) not null,
    updated_at            timestamp(6),
    uuid                  varchar(255) not null constraint twitch_client_tokens_public_id unique,
    access_token          varchar(255) not null constraint twitch_client_tokens_access_token unique,
    expiration_date_token timestamp(6) not null,
    o_auth_code           varchar(255) not null constraint twitch_client_tokens_oauth unique,
    refresh_token         varchar(255) not null constraint twitch_client_tokens_refresh unique,
    twitch_user_id        varchar(255) not null,
    twitch_username       varchar(255) not null,
    user_uuid             varchar(255) not null constraint twitch_client_tokens_link_user unique
);
