apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-paypal-microservice-deployment
  namespace: 'funixproductions-dev'
  labels:
    app: springboot
    service: payment-paypal

spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
      service: payment-paypal
  template:
    metadata:
      namespace: 'funixproductions-dev'
      annotations:
        build-time: "TIME-UPDATE-BUILD-FNG"
      labels:
        app: springboot
        service: payment-paypal
    spec:
      containers:
        - name: springboot-payment-paypal
          image: ghcr.io/funixproductions/funixproductions-api-payment-paypal:dev
          ports:
            - containerPort: 80
          resources:
            limits:
                memory: "300Mi"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: APP_PORT
              value: '80'
            - name: SPRING_PROFILES_ACTIVE
              value: 'dev'
            - name: PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: paypal-secret
                  key: paypal-client-id
            - name: PAYPAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: paypal-secret
                  key: paypal-client-secret

---

apiVersion: v1
kind: Service

metadata:
  namespace: 'funixproductions-dev'
  name: payment-paypal

spec:
  type: ClusterIP
  selector:
    app: springboot
    service: payment-paypal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
