create table twitch_event_sub_streamers
(
    id            bigint generated by default as identity primary key,
    created_at    timestamp        not null,
    updated_at    timestamp,
    uuid          varchar(255)     not null constraint UK_twitch_event_sub_streamers_public_id unique,
    streamer_id   varchar(255)     not null constraint UK_twitch_event_sub_streamers_st_id unique
);
