apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: funixproductions-api-certificate
  namespace: "funixproductions"
spec:
  secretName: funixproductions-api-certificate-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "api.funixproductions.com"
  dnsNames:
    - "api.funixproductions.com"
