# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy Dev Environment

on:
  push:
    branches: [ master ]

jobs:
  build-dev-maven:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - id: import_gpg
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        env:
          ENCRYPTION_KEY: hwJdNY1/yC3miXQR+Vw2V3qtt1e3FPJ2y62BKtROUJs=
          ENCRYPTION_IV: DKKyySzj8ao5WgraQpwj+A==
        run: mvn --batch-mode clean package -Dmaven.javadoc.skip -T 6

      - name: Publish Package Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: maven-packages
          path: modules/**/target/*.jar

  build-production-docker-images:
    needs: build-dev-maven
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download Package Artifacts
        uses: actions/download-artifact@v3
        with:
          name: maven-packages
          path: modules

      - name: Build funixproductions api docker images and push
        env:
          IMAGE_TAG: dev
        run: docker compose build --push

  deploy-to-kubernetes-cluster:
    needs:
      - build-production-docker-images

    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Update Kubernetes Dev Cluster
        run: cd kubernetes-dev && chmod +x ./deployServices.sh && ./deployServices.sh

  send-success-build-discord-notif:
    needs:
      - deploy-to-kubernetes-cluster

    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CI_STATUS }}
          DISCORD_USERNAME: FunixProductions-API-Deploy
          DISCORD_AVATAR: https://avatars.githubusercontent.com/u/99349214?s=200&v=4
        uses: Ilshidur/action-discord@master
        with:
          args: '✅ FunixProductions-API 🛠️**DEV** (dev.api.funixproductions.com) a bien été déployé sur le cluster Kubernetes !'
