# This is a basic workflow to help you get started with Actions

name: Push Maven realease

on:
  release:
    types: [created]

jobs:
  publish-maven-central:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: import_gpg
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

  build-pterodactyl-image-and-restart-prod:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push funixproductions api pterodactyl dockerfile
        run: |
          docker build . --tag ghcr.io/funixproductions/funixproductions-pteroq-api:latest -f pterodactyl.Dockerfile
          docker push ghcr.io/funixproductions/funixproductions-pteroq-api:latest

      - name: Send start signal to restart funixapi with new version
        run: |
          curl "https://${{ secrets.PTERODACTYL_DOMAIN }}/api/client/servers/4eeba516/power?signal=restart" \
            -X POST \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.PTERODACTYL_API_KEY }}'
