apiVersion: v1
kind: ConfigMap
metadata:
  namespace: 'funixproductions'
  name: postgres-config
data:
  postgres-url: 'postgres-db-service'
  postgres-port: '5432'
  postgres-db: 'funixproductions_db'
